// Generated / maintained for ORDO Staff + AsFix thermal plugin.
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

include ':asfix-thermal-print'
project(':asfix-thermal-print').projectDir = new File('../plugins/asfix-thermal-print/android')
